### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by hygkui**
快速开始时，使用hz new生成的代码里，go.mod里sonic的版本是1.3，在编译的时候会报错：

```
# github.com/bytedance/sonic/internal/loader
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:27:22: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:30:27: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:41:6: undefined: _Func
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:42:12: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:53:16: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata.go:79:26: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18") (no value) used as value
../../../../pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/loader.go:47:50: too many arguments in call to registerFunction
	have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
	want (string, uintptr, int, int, uintptr)
```
将sonic的版本改为1.4.0之后，就能成功编译了

#### What this PR does / why we need it (en: English/zh: Chinese):

en: 
zh:

### CODE REVIEW

**Comment by rogerogers** [comment]
Which version of golang and hz are you using? Work fine with me on go1.18.5 and hz version v0.2.0.
`go version`
`hz --version`

**Comment by hygkui** [comment]
go version : go version go1.19 darwin/amd64
hz version v0.2.0.

**Comment by rogerogers** [comment]
https://github.com/cloudwego/hertz/issues/212

We may need make a full test, then upgrade the Hertz dependencies

**Comment by li-jin-gou** [comment]
@hygkui  refer to https://github.com/cloudwego/hertz/pull/191 and you can use `go get github.com/bytedance/sonic ` upgrade sonic's version
